import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/app/theme-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full h-auto bg-white ${GeistSans.className}`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
      <Toaster />
    </html>
  );
}
